# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8483f2809f803a2d7ac3808b0f7cfb51121cf244fd7554d02cb9f0f5b3cdc1b5871b1c3d67883abcbcf41751019701e784445dd831700db513813e115f9d568c

test:
  secret_key_base: 37a0b0344962f3f0127cffa314838796762656877adb8a60b9f6fcc803aae0d1aadc47e5fb889a9527e940b769a3e4d5f2be4d29d0ac5fb53d73490ebb684c69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
